# This is a basic workflow to help you get started with Actions
name: Build de la aplicacion

on:
  #Defino el evento de ejecucion al que responde la action
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Selecciono el ejecutor
    runs-on: ubuntu-latest

    # Definicion de pasos a ejecutar
    steps:
      # Extrae su repositorio en $GITHUB_WORKSPACE, para que su trabajo pueda acceder a él
      - uses: actions/checkout@v4

      # Ejecucion de un Script de una linea
      - name: Install dependencies
        run: |
          echo Installing dependencies...
          Run go mod tidy,
          echo Dependencias instaladas.

      # Ejecucion de un Script de varias lineas
      - name: Run aplicacion
        run: |
          echo Corriendo Aplicacion,
          Run go run main.go,
          echo Prueba y deploy del programa exitosa.
